openapi: 3.0.0
info:
  title: Kanban Board Service
  version: 1.0.0
  description: A collaborative task management system designed around the Kanban methodology. This project supports multiple users, projects, and tasks with real-time members assignment and role-based access.

servers:
  - url: http://192.168.0.106:3200/kanban-svc/api/v1.0
    description: Local development server

components:
  schemas:
    healthCheckData:
      title: Schema for Health Check Data
      type: object
      properties:
        uptime:
          type: string
        timestamp:
          type: string
        hostname:
          type: string

    healthCheckResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        message:
          type: string
          example: "Success"
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/healthCheckData"

    internalServerErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        statusCode:
          type: integer
          example: 500
        message:
          type: string
          example: "Internal Server Error"
        data:
          type: array
        error:
          type: array
        stack:
          type: string

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Service Health Check
      description: Check the health status of the service.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthCheckResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/internalServerErrorResponse"
